FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./
RUN npm ci --prefer-offline

COPY prisma ./prisma
RUN npx prisma generate

CMD ["npx", "prisma", "migrate", "deploy"]
